{{- if .Values.env }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-env
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
type: Opaque
stringData:
{{- range $key, $value := .Values.env }}
  {{ $key }}: {{ $value | quote }}
{{- end }}
{{- end }}
